name: build-pr

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Extract secrets from Keeper
        uses: Keeper-Security/ksm-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            ${{ vars.KEEPER_SONARCLOUD_RECORD_ID }}/field/password > env:SONAR_TOKEN

      - name: Build and test
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{env.SONAR_TOKEN}}
        run: ./mvnw -B clean verify sonar:sonar

      - run: mkdir staging && cp target/*.zip staging
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Connectors
          path: staging
