name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Extract secrets from Keeper
      uses: Keeper-Security/ksm-action@v1
      with:
        keeper-secret-config: ${{ secrets.KSM_CONFIG }}
        secrets: |
          ${{ vars.KEEPER_SONARCLOUD_RECORD_ID }}/field/password > env:SONAR_TOKEN

    - name: Build and test
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{env.SONAR_TOKEN}}
      run: ./mvnw -B clean verify sonar:sonar

    - run: mkdir staging && cp target/*.zip staging
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Connectors
        path: staging
