name: Release

run-name: ${{ github.event.inputs.version }} Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release. Used as tag name.'
        required: true
        default: 'x.y.z'
      update_marketplace:
        description: 'Update marketplace after release'
        type: boolean
        default: false

jobs:
  release:
    uses: bonitasoft/github-workflows/.github/workflows/_reusable_release_connector.yml@main
    with:
      release-version: ${{ github.event.inputs.version }}
    secrets: inherit

  notify-marketplace:
    needs: release
    if: ${{ inputs.update_marketplace }}
    runs-on: ubuntu-24.04
    steps:
      - name: Notify marketplace
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: bonitasoft/bonita-marketplace
          event-type: new-connector-release
          client-payload: >-
            {
              "artifactId": "bonita-connector-database",
              "version": "${{ inputs.version }}",
              "bonitaMinVersion": "7.13.0"
            }
